### ISSUE TITLE
tags and log levels

### ISSUE THREAD

**Issue by ns3777k** [lancespeelmon/good-winston#9]
Hey.

I've been trying to make use of `good-winston`, but ran into a problem. I set `request_level` to be `info`.
Imagine a route that goes to the database (or any other source of data i.e. remote http service) and in 99% it succeeds. But in case it's not you probably wanna log that:

```js
async function createUser(request, reply) {
    try {
        const id = await storage.addUser({...});
        reply({id}).state('id', id);
    } catch (e) {
        request.log('error', e);
        reply({error: 'Something bad happened'});
    }
```

When it comes to logging `good-winston` checks only `data.event` that in this case will be `request` and the log level will be `info`, but I passed `error` as a tag so I consider this `request.log` to be an error.

IMO tags should be taken into account. What do you think?

Thanks for sharing the project :+1:

**Comment by ambrons** [comment]
I could be completely off base here, but it's possible that the intent is to map the internal log messages from hapi to winston log levels so they're reported generally the right way with winston.

That said instead of using request.server.log you'd use winston directly to report your error?

Like I said I could be totally looking at this wrong, but I do see your point that ideally the tags would map to log levels.

**Comment by lancespeelmon** [comment]
Yes @ambrons you are correct - that was the intention. I like @ns3777k 's idea - it sounds like it would make for a good pull request. :) Best, L
